grpc_server_cfg:
  host: "127.0.0.1"
  port: 8086
  network: "tcp"

httpserver_cfg:
  host: "127.0.0.1"
  port: 8080

database_cfg:
  database_user_name: "game_app"
  database_password: "game_app_pass"
  database_name: "game_app_db"
  database_host: "127.0.0.1"
  database_parse_time: true
  database_port: 3308

redis_cfg:
  network_cfg: "tcp"
  host_cfg: "127.0.0.1"
  port_cfg: 6380
  password_cfg: "password1999"
  db_cfg: 0

auth_cfg:
  sign_key: "jwt_secret_key"
  access_expiration_time: 24h    # 1 day
  refresh_expiration_time: 168h  # 7 days
  access_subject: "at" # access token
  refresh_subject: "rt"  # refresh token

app_cfg:
  gracefully_shutdown_timeout: 5s # 5 second

matching_cfg:
  context_time_out: 3m
  online_threshold_duration: 3m
  waiting_time_out: 5m

presence_cfg:
  expiration_time: 30m
  prefix: "presence"

scheduler_cfg:
  crontab: "*/1 * * * *"

matching_repo_cfg:
  waiting_list_prefix: "waiting-list"
  context_timeout_ZRem: 5s

grpc_presence_client_cfg:
  host: "127.0.0.1"
  port: 8086
  network: "tcp"

publisher_cfg:
  context_timeout_redis_pub: 3s

logger_cfg:
  file_name: "logs/app.log"
  max_size: 30
  max_age: 7
  max_backups: 3
  compress: true
  simpling_core_tick: 1m
  simpling_core_first: 100
  simpling_core_thereafter: 100