app_cfg:
  gracefully_shutdown_timeout: 10s # 5 second
  debug_mod: true # If debug_mod is true, it means that profiling server is enabled and should be set pprof_cfg.

database_cfg:
  database_driver_name: "mysql"
  database_conn_max_lifetime: 3m
  database_max_open_connections: 10
  database_max_idle_connections: 10
  database_user_name: "game_app"
  database_password: "game_app_pass"
  database_name: "game_app_db"
  database_host: "127.0.0.1"
  database_parse_time: true
  database_port: 3308

redis_cfg:
  network_cfg: "tcp"
  host_cfg: "127.0.0.1"
  port_cfg: 6380
  password_cfg: "password1999"
  db_cfg: 0

jwt_cfg:
  sign_key: "jwt_secret_key"
  access_expiration_time: 24h    # 1 day
  refresh_expiration_time: 168h  # 7 days
  access_subject: "at" # access token
  refresh_subject: "rt"  # refresh token
  sign_method: "HS256"

matching_cfg:
  context_time_out: 3m
  online_threshold_duration: 3m
  waiting_time_out: 5m

game_svc_cfg:
  num_workers: 5

presence_cfg:
  expiration_time: 30m
  prefix: "presence"

scheduler_cfg:
  crontab: "*/1 * * * *"

matching_repo_cfg:
  waiting_list_prefix: "waiting-list"
  context_timeout_ZRem: 5s

publisher_cfg:
  context_timeout_redis_pub: 3s

subscriber_cfg:
  queue_buffer_size: 100

logger_cfg:
  file_name: "logs/app.log"
  max_size: 30
  max_age: 7
  max_backups: 3
  compress: true
  simpling_core_tick: 1m
  simpling_core_first: 100
  simpling_core_thereafter: 100
  level: "info" # e.g. "debug", "info", "warn", "error"

httpserver_cfg:
  host: "127.0.0.1"
  port: 8080

ws_cfg:
  host: ""
  port: 8090
  allowed_origins_websocket:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  send_buffer_size: 1024
  gracefully_shutdown_timeout: 10s
  websocket_pattern: "/ws"

metrics_cfg:
  host: "127.0.0.1"
  port: 2112

pprof_cfg:
  host: "127.0.0.1"
  port: 2111

grpc_presence_server_cfg:
  host: "127.0.0.1"
  port: 8086
  network: "tcp"

grpc_presence_client_cfg:
  host: "127.0.0.1"
  port: 8086
  network: "tcp"

