httpserver_cfg:
  host: "127.0.0.1"
  port: 8080

auth_cfg:
  sign_key: "jwt_secret_key"
  access_expiration_time: 24h    # 1 day
  refresh_expiration_time: 168h  # 7 days
  access_subject: "at" # access token
  refresh_subject: "rt"  # refresh token

database_cfg:
  database_user_name: "game_app"
  database_password: "game_app_pass"
  database_name: "game_app_db"
  database_host: "127.0.0.1"
  database_parse_time: true
  database_port: 3308
