services:
  db:
    image: mysql:8
    ports:
      - "3308:3306"
    container_name: gameapp_db
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    cap_add:
      - SYS_NICE
    environment:
      - "MYSQL_ROOT_PASSWORD=game_app_root"
      - "MYSQL_USER=game_app"
      - "MYSQL_PASSWORD=game_app_pass"
      - "MYSQL_DATABASE=game_app_db"
    volumes:
      - db_vol:/var/lib/mysql
volumes:
  db_vol: