// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: created_game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatedGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        uint64                 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerIds     []uint64               `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedGame) Reset() {
	*x = CreatedGame{}
	mi := &file_created_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedGame) ProtoMessage() {}

func (x *CreatedGame) ProtoReflect() protoreflect.Message {
	mi := &file_created_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedGame.ProtoReflect.Descriptor instead.
func (*CreatedGame) Descriptor() ([]byte, []int) {
	return file_created_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreatedGame) GetGameId() uint64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CreatedGame) GetPlayerIds() []uint64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

var File_created_game_proto protoreflect.FileDescriptor

const file_created_game_proto_rawDesc = "" +
	"\n" +
	"\x12created_game.proto\x12\x04game\"E\n" +
	"\vCreatedGame\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x04R\x06gameId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x04R\tplayerIdsBAZ?golang.project/go-fundamentals/gameapp/contract/goprotobuf/gameb\x06proto3"

var (
	file_created_game_proto_rawDescOnce sync.Once
	file_created_game_proto_rawDescData []byte
)

func file_created_game_proto_rawDescGZIP() []byte {
	file_created_game_proto_rawDescOnce.Do(func() {
		file_created_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_created_game_proto_rawDesc), len(file_created_game_proto_rawDesc)))
	})
	return file_created_game_proto_rawDescData
}

var file_created_game_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_created_game_proto_goTypes = []any{
	(*CreatedGame)(nil), // 0: game.CreatedGame
}
var file_created_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_created_game_proto_init() }
func file_created_game_proto_init() {
	if File_created_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_created_game_proto_rawDesc), len(file_created_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_created_game_proto_goTypes,
		DependencyIndexes: file_created_game_proto_depIdxs,
		MessageInfos:      file_created_game_proto_msgTypes,
	}.Build()
	File_created_game_proto = out.File
	file_created_game_proto_goTypes = nil
	file_created_game_proto_depIdxs = nil
}
